architecture: standalone
auth:
  existingSecret: postgresql
  username: psys-dev
  database: padmini
primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30432
  persistence:
    enabled: true
    size: 25Gi
    storageClass: ""
  resourcesPreset: "nano"