apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/graitcloud/apps.git
    targetRevision: HEAD
    path: cilium-network-policies
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true