apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-for-network-permission-in-restricted-ns
  annotations:
    description: "Allows all traffic only for pods labeled 'padmini.systems/network-permission: allow' in namespaces labeled 'access=restricted'."
spec:
  endpointSelector:
    matchExpressions:
      - key: padmini.systems/network-permission
        operator: In
        values: ["allow"]
      - key: io.cilium.k8s.namespace.labels.access
        operator: In
        values: ["restricted"]

  ingress:
  - {}

  egress:
  - {}
