apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cluster-ingress-managed-baseline
  labels:
    managed-by: platform
    component: ingress-nginx
  annotations:
    description: "Baseline policy for ingress controllers: allow host access on 10254 and egress to kube-apiserver on external IP:6443"
spec:
  endpointSelector:
    matchExpressions:
      - key: padmini.systems/tenant-resource-type
        operator: In
        values: ["ingress"]
      - key: padmini.systems/network-permission
        operator: In
        values: ["allow"]

  ingress:
    # Allow host (internal IP) to access ingress controller on port 10254
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "10254"
              protocol: TCP
    
    # Allow cert-manager pods to access ingress controller on port 80
    - fromEndpoints:
        - matchLabels:
            instance: cert-manager
          matchExpressions:
            - key: k8s:io.kubernetes.pod.namespace
              operator: In
              values: ["cert-manager"]
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

  egress:
    # Allow ingress controller to access kube-apiserver on external IP (public IP) port 6443
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
