apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: deny-all-restricted-namespaces
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.access: restricted
  ingressDeny:
  - {}
  egressDeny:
  - {}