apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: restricted-namespaces-egress-dns-policy
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.access: restricted
    matchExpressions:
      - key: padmini.systems/network-permission
        operator: NotIn
        values: ["allow"]

  ingress:
  - fromEndpoints:
    - matchLabels:
        padmini.systems/api: broadcast-api

  egress:
  - toEndpoints:
    - matchLabels:
        k8s:k8s-app: kube-dns
        k8s:io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
